urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout
from reddit.feeds import Latest, Detail, User

feeds = {
    'latest': Latest,
    'details': Detail,
    'user' : User,
}

urlpatterns = patterns('reddit.views',
    (r'^$','index'),
    (r'^submit/$','submit_link'),
    (r'^submitted/$','link_submitted'),
    (r'^comment/$','submit_comment'),
    (r'^details/(?P<link_id>\d+)/$','show_details'),
    (r'^comment/(?P<comment_id>\d+)/$','show_comment'),
    (r'^save/(?P<link_id>\d+)/$','save_link'),
    (r'^upvote/(?P<link_id>\d+)/$','vote_link', {'up':True}),
    (r'^downvote/(?P<link_id>\d+)/$','vote_link', {'up':False}),
    (r'^user/(?P<user_name>\w+)/$','user_details'),
    (r'^tags/(?P<tag_text>\w+)/$','show_tagged_links'),
    (r'^user/(?P<user_name>\w+)/saved/$','saved_links'),
    (r'^user/(?P<user_name>\w+)/liked/$', 'liked_links', {'up':True}),
    (r'^user/(?P<user_name>\w+)/disliked/$', 'liked_links', {'up':False}),
    (r'^user/(?P<user_name>\w+)/comments/$','user_comments'),    
    (r'^accounts/profile/$','user_details'),
    (r'^accounts/profile/saved/$','saved_links'),
    (r'^accounts/profile/liked/$','liked_links', {'up':True}),
    (r'^accounts/profile/disliked/$','liked_links', {'up':False}),
    (r'^accounts/profile/comments/$','user_comments', ),
    (r'^test/$','test'),        
    (r'^register/$','register'), 
    (r'^accounts/$','index'),    #Todo 
    # Uncomment this for admin:
    (r'^admin/', include('django.contrib.admin.urls')),
  
)

urlpatterns += patterns('',
    (r'^accounts/login/$',  login, {'template_name': 'registration/login.html'}),
    (r'^accounts/logout/$', logout),                  
                )

urlpatterns += patterns('',
        (r'^foo/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'C:/django/redpy/templates/media'}),
        (r'^js/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'C:/django/redpy/templates/js'}),
    )

#feeds
urlpatterns += patterns('',
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
    )

reddit/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django import newforms as forms
from django.newforms import form_for_model
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.models import User
from django import oldforms as oldforms
from django.contrib.auth.forms import UserCreationForm
from django.utils.html import escape
from MySQLdb import IntegrityError #Todo

from reddit.models import Link
from reddit.models import Comment
from reddit.models import UserVotes, SavedLink, Tags
from reddit import defaults

import random
import datetime
import time
from urlparse import urlparse

def index(request):
            
    data = []
    links = Link.objects.all().order_by('-points', '-added_on')
    links, page = paginate_links(request, links)
    for link in links:
      print _populate_link_data(link, request.user)
      data.append(link)
      #db_data.append(link.link)                
    return render_to_response('index.html', {'links':data, 'page':page, }, context_instance=RequestContext(request))
    
def show_details(request, link_id, off = 0):        
    try:
        off = request.GET['offset']
    except:
        off = '0'
    off = eval(off)    
    last = off+defaults.comments_per_page
    page = {}  
                
    request.session['link_id'] = link_id
    link = Link.objects.get(id=link_id)
    _populate_link_data(link, request.user)
    comments = Comment.objects.filter(link = link)[off:last]
    _populate_comments_data(comments)
    comment_form = submit_comment(request)   
    tag_form = tag_link(request)
    tags = Tags.objects.filter(link = link) 
    print 'foo'     
 
    
    if off > 0:
        page['has_prev'] = True
        page['prev'] = off - defaults.comments_per_page
    if last < Comment.objects.filter(link = link).count():
        page['has_next'] = True
        page['next'] = off + defaults.comments_per_page 
           
    if request.method == 'POST':
        return HttpResponseRedirect('.')
    return render_to_response('details.html', {'link':link, 'comments':comments, 'comment_form':comment_form, 'tag_form':tag_form, 'tags': tags, 'page':page, 'link_id':link_id}, context_instance=RequestContext(request))
 

def show_tagged_links(request, tag_text):
        
    tags = Tags.objects.filter(tag = tag_text)
    tags, page = paginate_links(request, tags)
    links = []
    for tag in tags:
        links.append(tag.link)
    _populate_links_data(links, request.user)
    
            
    return render_to_response('index.html', {'links':links, 'page':page}, context_instance=RequestContext(request))
        
def user_details(request, user_name = None,):        
    
    if user_name == None:
        user_name = request.user.username
        subtitle = 'Your submitted links'
        otherprofile  = False  
    else:
        subtitle = "%s's submitted links" % user_name
        otherprofile  = True 
    user = User.objects.get(username = user_name)
    links = Link.objects.filter(user = user)[:10]
    _populate_links_data(links, request.user)
    
    return render_to_response('user.html', {'links':links, 'subtitle':subtitle, 'otherprofile':otherprofile, 'user_name':user_name}, context_instance=RequestContext(request))    

def saved_links(request, user_name = None, ):      
    if user_name == None:
        user_name = request.user.username
        subtitle = 'Your saved links' 
        otherprofile  = False          
    else:
        subtitle = "%s's saved links" % user_name
        otherprofile  = True         
    user = User.objects.get(username = user_name)
    voted_links = SavedLink.objects.filter(user = user)
    voted_links, page = paginate_links(request, voted_links,)
    links = [el.link for el in voted_links]
    _populate_links_data(links, request.user)
    
    return render_to_response('user.html', {'links':links, 'page':page, 'subtitle': subtitle, 'otherprofile':otherprofile, 'user_name':user_name}, context_instance=RequestContext(request))
        
def liked_links(request, up, user_name = None, ):       
    if user_name == None:
        user_name = request.user.username
        greet = 'Your'
        otherprofile  = False          
    else:
        greet = "%s's" % user_name
        otherprofile  = True         
    user = User.objects.get(username = user_name)
    voted_links = UserVotes.objects.filter(user = user, upvote = up)
    voted_links, page = paginate_links(request, voted_links,)
    links = [el.link for el in voted_links]
    _populate_links_data(links, request.user)
    if up:
        subtitle = '%s liked links' % greet
    else:
        subtitle = '%s disliked links' % greet
    return render_to_response('user.html', {'links':links, 'page':page, 'subtitle':subtitle, 'otherprofile':otherprofile, 'user_name':user_name}, context_instance=RequestContext(request))

def paginate_links(request, query_set):
    maximum = query_set.count()
    try:
        off = request.GET['offset']
    except:
        off = '0'
    off = eval(off)    
    last = off+defaults.links_per_page
    page = {}  
    paged_query_set = query_set[off:last]        
    
    if off > 0:
        page['has_prev'] = True
        page['prev'] = max(off - defaults.links_per_page, 0)
    if last < maximum:
        print 'hol'
        page['has_next'] = True
        page['next'] = off + defaults.links_per_page 
        
    return paged_query_set, page
    
def show_comment(request, comment_id):
    comments = Comment.objects.filter(id = comment_id)
    _populate_comments_data(comments)    
    return render_to_response('comment.html', {'comments': comments, 'otherprofile':otherprofile}, context_instance=RequestContext(request))

def user_comments(request, user_name = None):    
    if user_name == None:
        user_name = request.user.username
        subtitle = "Your comments"
        otherprofile  = False  
    else:
        subtitle = "%s comments" % user_name
        otherprofile  = True 
    user = User.objects.get(username = user_name)
    comments = Comment.objects.filter(user = user)
    _populate_comments_data(comments)        
    return render_to_response('comment.html', {'comments': comments, 'subtitle':subtitle, 'otherprofile':otherprofile }, context_instance=RequestContext(request))
    

@login_required
def vote_link(request, link_id, up):
    link = Link.objects.get(id = link_id)
    voted = link.vote(request.user, up)                  
    if voted == True:
            return HttpResponse(str(link.id))
    return HttpResponse(str(-1))


@login_required
def submit_link(request):
    class SubmitLink(forms.Form):
        link = forms.URLField()
        text = forms.CharField(widget=forms.Textarea)
    if request.method == 'GET':
        sub_f = SubmitLink()
        return render_to_response('submit.html', {'sub_f': sub_f,}, context_instance=RequestContext(request))
    elif request.method =='POST':
        try:
            sub_f = SubmitLink(request.POST)
            if sub_f.is_valid():
                link = request.POST['link']
                text = request.POST['text']
                user_id = request.user
                the_link = Link.objects.create_link(link = link, text = text, user = user_id)
                the_link.save()  
                return HttpResponseRedirect(the_link.get_absolute_url())      
            else:
                return render_to_response('submit.html', {'sub_f': sub_f,})
        except IntegrityError:
            links = Link.objects.filter(link = link)
            for the_link in links:
                return HttpResponseRedirect(the_link.get_absolute_url())
            
@login_required
def save_link(request, link_id):        
    try:
        link = Link.objects.get(id = link_id)
        saved_link = SavedLink(user = request.user, link = link)
        saved_link.save()
        return HttpResponse(str(link.id))
    except IntegrityError :
        return HttpResponse(str(-1))
 

@login_required
def user_details_x(request, user_name = None):
    return user_details(request, user_name = None)
    
@login_required    
def saved_links_x(request, user_name = None):        
    return saved_links(request, user_name = None)

@login_required    
def liked_links_x(request, up, user_name = None, ):
    return liked_links(request, up, user_name = None, )    

@login_required
def submit_comment(request):
    class CommentForm(forms.Form):
        text = forms.CharField(widget=forms.Textarea)
    if request.method == 'GET':
        com_f = CommentForm()
        action = '.'
        method = 'post'
        #return wrap_form(com_f, action, method)
        return com_f
    elif request.method == 'POST':
        com_f = CommentForm(request.POST)
        action = '.'
        method = 'post'
        if com_f.is_valid():
            link_id = request.session['link_id']
            link = Link.objects.get(id = link_id)
            user = request.user
            text = request.POST['text']
            comment = Comment.objects.create_comment(link = link, user = user, text = text, )
            comment.save()
            #return wrap_form(com_f, action, method)            
            return com_f
        else:
            #return wrap_form(com_f, action, method)
            return com_f
@login_required      
def tag_link(request):
    print 'tag_form'
    class TagForm(forms.Form):
        tags = forms.CharField()
    if request.method == 'GET':
        tag_f = TagForm()
        return tag_f
    elif request.method == 'POST':
        tag_f = TagForm(request.POST)
        if tag_f.is_valid():
            link_id = request.session['link_id']

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>

<!-- Dependency -->
<script src="http://yui.yahooapis.com/2.3.0/build/yahoo/yahoo-min.js"></script>

<!-- Used for Custom Events and event listener bindings -->
<script src="http://yui.yahooapis.com/2.3.0/build/event/event-min.js"></script>

<!-- Source file -->
<script src="http://yui.yahooapis.com/2.3.0/build/connection/connection-min.js"></script>

<!-- Source file -->
<script src="http://yui.yahooapis.com/2.3.0/build/dom/dom-min.js"></script>

<script src="/js/modhandler.js">


    <title>{% block title %}What's new online{% endblock %}</title>

	<link rel="stylesheet" type="text/css" href="/foo/style.css" media="screen" />


</head>

<body>
<div id="header">
<h1>What's cookin'</h1>
 <div id="menu">
  <ul id="nav">
   <li><a href="/">home</a></li>
   <li><a href="/submit/">submit</a></li>
   <li>			 
				 {% if user.is_authenticated %}
				 <a href="/accounts/logout/">logout</a>
				 {% else %}
				 <a href="/accounts/login/">login</a>
				 {% endif %}
  </li>
     
				 {% if user.is_authenticated %}
				 <li>
				 <a href="/accounts/profile/">profile</a>
				 </li>
				 {% endif %}
  </ul>
 </div>
</div>

	<div id="left">

			
	<div class="box">
	<strong>
	{% if user.is_authenticated %}
	Howdy {{ user.username }} ?
	<br />
    <br />
    {% block sidebar %}
    <ul>
	  <li> 
	  <a href="/accounts/profile/">
	  submitted
	  </a>
	  </li>
	  <li> 
	  <a href="/accounts/profile/saved/">
	  saved
	  </a>
	  </li>
	  <li>
	  <a href="/accounts/profile/liked/">
	  liked
	  </a>
	  </li>
	  <li>
	  <a href="/accounts/profile/disliked/">
	  disliked
	  </a>
	  </li>
	  <li>
	  <a href="/accounts/profile/comments/">
	  comments
	  </a>
	  </li>
    </ul>
    {% endblock %}
	{% else %}
    Hey guest. <br />
    <a href="/accounts/login/">login</a> or
	<a href="/register/">register</a>
	{% endif %}
	</strong>
	</div>
		
	</div>

    <div id="content">

        {% block content %}{% endblock %}
    </div>
	<div id="footernav">

	{% block footernav %}
	<span class="fnav">
	{% if page.has_prev %}
	<a href="{{ request.path }}?offset={{page.prev}}">&laquo;prev</a>
	{% endif %}
	</span>
	<span class="fnav">
	{% if page.has_next %}
	<a href="{{ request.path }}?offset={{page.next}}">next&raquo;</a>
	{% endif %}
	{% endblock %}
	</span>

	</div>

	{% block footer %}
	<div id="footer">
	<a href="/help/">help</a>
	{% block feed %}
	<a href="/feeds/latest/">feed</a>
	{%endblock%}
    </div>
	{% endblock %}
</body>
</html>

templates/comment.html
{% extends "base.html" %}
{% block content %}
<div id="umenu">
  <ul id="unav">
   <li><a href="#">Submitted </a></li>
   <li><a href="#">Submitted </a></li>
   <li><a href="#">Liked </a></li>
   <li><a href="#">Disliked</a></li>
   <li><a href="#">Comments</a></li>
  </ul>
</div>
<br />
<h3>
	{{subtitle}}
</h3>
<ul>
 {% for comment in comments %}
     <li>
	 {% include "comments.html" %} {% include "comment_controls.html" %}
	 </li>
{% endfor %}	
</ul>
{% endblock %}

templates/comment_controls.html
<div class="controls">
by
<a href="/user/{{comment.user.username}}/">{{ comment.user.username}}</a>
 {{comment.time_elapsed}} ago 
<a href="{{comment.get_absolute_url}}">permalink</a>
</div>

templates/comments.html
{% load markup %}
{{ comment.text|markdown }}

templates/details.html
{% extends "base.html" %}

{% block title %}{{ link.text }}{% endblock %}

{% block content %}

<div class="tags">
<strong>
Tags:
</strong>
<ul>

{% for tag in tags %}
<li>
<a href="{{tag.get_absolute_url}}" class="taglink">
{{ tag.tag }}
</a>
</li>
{%endfor %}

</ul>


{% if user.is_authenticated %}
<form method="post" action=".">
<table>{{ tag_form }}</table>
<button class='btn' type='submit'>Tag it</button>
</form>
{%endif%}

</div>
    {% include "link.html" %}
    {% include "link_controls.html" %}

{% if user.is_authenticated %}
<form method="post" action=".">
<table>{{comment_form}}</table>
<button class='btn' type='submit'>Comment</button>
</form>
{% else %}

<form method="post" action=".">
<table><tr><th><label for="id_text">Text:</label></th><td><textarea name="text" id="id_text" readonly='readonly'>Please login to submit a comment</textarea></td></tr></table>
<button class='btn' type='submit' disabled='disabled'>Comment</button>
</form>

{% endif %}


<ul>
{% for comment in comments %}
  <li>
     {% include "comments.html" %} {% include "comment_controls.html" %}
	</li>
{% endfor %}
</ul>
{% endblock %}

{% block feed %}
	<a href="/feeds/details/{{link_id}}/">feed</a>
{%endblock%}

templates/index.htm
{% extends "base.html" %}

{% block title %}My amazing blog{% endblock %}

{% block content %}
<ul>
{% for link in links %}
  <li>
	{{ link.text }}
	</li>
{% endfor %}
</ul>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}Let's get cookin'{% endblock %}

{% block content %}
<ul>

{% for link in links %}
  <li>
    {% include "link.html" %}
    {% include "link_controls.html" %}

  </li>
{% endfor %}
</ul>
{% endblock %}

templates/link.html
    <div class="linkrow">
	{% if link.upvoted %}
	<a href="#" id="uplink{{link.id}}" onclick="mod_link({{link.id}}, 1)"><img src="/foo/upped.png" id="uplink{{link.id}}img" /></a>
	{% else %}
    <a href="#" id="uplink{{link.id}}" onclick="mod_link({{link.id}}, 1)"><img src="/foo/up.png" id="uplink{{link.id}}img" /></a>
	{% endif %}
    <a href="#" id="downlink{{link.id}}" onclick="mod_link({{link.id}}, 0)"><img src="/foo/down.png" id="downlink{{link.id}}img" /></a>
    <strong>
    <a href="{{link.link}}"> {{ link.text }} </a>
    </strong>
	<span class="linkdomain">({{link.domain}})</span>
    <br />
	</div>

templates/link_controls.html
{% load humanize %}   
    <div class="controls">
	{{ link.points|apnumber}} points added {{link.time_elapsed}} ago, by 
	<a href="/user/{{link.user.username}}/" class="user">{{link.user.username}}</a>
	<a href="/details/{{ link.id }}/">{{link.num_comments}} comments</a> 
	{% if not link.saved %}
	<span id="save{{link.id}}"><a href="#" class="savelink"  onclick="save_link({{link.id}})">save this</a></span>
	{% else %}
    <span id="save{{link.id}}">saved</span>
	{% endif %}
	<br />
   </div>

templates/saved.html
{% extends "base.html" %}

{% block title %}User - {{ user.username }}{% endblock %}

{% block content %}
<h3>
	{% block subtitle %} {{subtitle}} {% endblock %}
</h3>

<ul>
{% for link in links %}
  <li>
    {% include "link.html" %}
    {% include "link_controls.html" %}
  </li>
{% endfor %}
</ul>
{% endblock %}

templates/submit.html
{% extends "base.html" %}

{% block title %}Submit{% endblock %}

{% block content %}

<form action="/submit/" method="post">

   <table>
   {{ sub_f.as_table }}
   </table>

	 <button class='btn' type='submit'>submit link!</button>
</form>

{% endblock %}

templates/test.html
{% extends "base.html" %}

{% block title %}My amazing blog{% endblock %}

{% block content %}
{% for entry in blog_entries %}
    <h2>{{ entry.title }}</h2>
    <p>{{ entry.body }}</p>
		<p>{{ entry.dooby }}</p>
{% endfor %}
{% endblock %}

templates/user.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}User - {{ user.username }}{% endblock %}

{% block content %}

{% if otherprofile %}
<div id="umenu">
  <ul id="unav">
   <li><a href="/user/{{ user_name }}/">Submitted </a></li>
   <li><a href="/user/{{ user_name }}/saved/">Saved </a></li>
   <li><a href="/user/{{ user_name }}/liked/">Liked </a></li>
   <li><a href="/user/{{ user_name }}/disliked/">Disliked</a></li>
   <li><a href="/user/{{ user_name }}/comments/">Comments</a></li>
  </ul>
</div>
{% endif %}
<br />

<h3>
	{{subtitle}}
</h3>

<ul>
{% for link in links %}
  <li>
    {% include "link.html" %}
    {% include "link_controls.html" %}
  </li>
{% endfor %}
</ul>
{% endblock %}

templates/user_link.html
<a href="/user/{{link.user.username}}/" class="user">{{link.user.username}}</a>